export const eventsData =
    [
        { id: 6, event: [{ subtitle: "Reprehenderit proident reprehenderit Lorem eu ullamco sint ea culpa proident.", id: 6, text: "Laborum tempor in voluptate labore enim exercitation voluptate incididunt consectetur qui magna sit laboris. Mollit pariatur ad dolor occaecat adipisicing incididunt pariatur officia. Et pariatur sit proident ea est nisi quis. Officia tempor adipisicing nostrud quis irure deserunt pariatur tempor cillum excepteur eu labore esse anim. Esse anim adipisicing aliquip voluptate do voluptate. Exercitation elit eiusmod exercitation in ipsum minim voluptate tempor eiusmod aliqua velit deserunt." }], date: "14/10/22" },
        { id: 7, event: [{ subtitle: "Reprehenderit nulla duis ipsum ut ullamco amet.", id: 7, text: "In ullamco qui pariatur veniam in id amet do do do enim ullamco sint. Id anim velit exercitation ut exercitation mollit. Quis in laboris laborum reprehenderit. Enim cupidatat laborum eu enim ea nulla ad quis minim incididunt quis cupidatat pariatur. Reprehenderit dolore ipsum qui pariatur voluptate cillum pariatur. Duis exercitation ipsum non sunt aute ut ea." }], date: "17/10/22", },
        { id: 8, event: [{ subtitle: "Adipisicing officia do occaecat anim consequat occaecat do dolor.", id: 8, text: "Aute in dolor veniam cupidatat. Proident consectetur exercitation qui ut Lorem dolore amet. Aliquip aliqua nisi ipsum anim qui esse enim laborum adipisicing pariatur. Reprehenderit ea excepteur nisi laborum. Deserunt officia magna laboris reprehenderit dolore laborum." }], date: "03/11/22", },
        { id: 9, event: [{ subtitle: "Veniam consequat nisi eu tempor laboris incididunt ea fugiat commodo laborum.", id: 9, text: "Pariatur amet consectetur nulla ipsum culpa consectetur amet cupidatat minim cillum ullamco voluptate. Irure sint nisi sunt quis in excepteur magna commodo officia. Consequat esse dolor in magna velit nisi veniam deserunt sint cillum voluptate tempor." }, { subtitle: "Officia ut nulla nisi mollit dolore ipsum id eu ipsum sunt quis ex do.", id: 8, text: "Eu cillum duis qui aute anim duis sint labore reprehenderit veniam occaecat voluptate nulla. Occaecat velit sit deserunt commodo reprehenderit amet voluptate incididunt mollit. Est dolore velit anim sint commodo sunt aliqua sunt non ullamco est. Esse laborum id sint pariatur veniam nostrud non sunt irure officia." }], date: "14/11/22" },
        { id: 10, event: [{ subtitle: "Ad enim ipsum reprehenderit tempor in in sit labore veniam in quis in.", id: 10, text: "Cillum enim commodo duis esse ullamco elit veniam nisi aute consequat eu tempor commodo eiusmod. Excepteur enim pariatur sint nisi minim. Esse nulla deserunt fugiat enim ea exercitation nulla nostrud." }], date: "17/11/22" },
        { id: 11, event: [{ subtitle: "Ex veniam quis amet cillum cillum eiusmod labore esse do occaecat do dolore.", id: 11, text: "Incididunt excepteur officia ipsum excepteur non quis. Ad veniam ex nulla exercitation adipisicing laboris. Velit magna velit occaecat ut reprehenderit deserunt aute proident voluptate et in ipsum. Occaecat fugiat est exercitation labore ex. Esse in Lorem irure consectetur adipisicing tempor proident eu Lorem et ullamco sit irure. Voluptate dolore quis quis reprehenderit veniam." }], date: "03/12/22" },
    ]

export const daysOfTheWeek = ["MON", "TUE", "WED", "THUR", "FRI", "SUN", "SAT"]
